In [ ]:
import requests
from bs4 import BeautifulSoup
import re
import dateutil

In [ ]:
result = requests.get("https://www.aishub.net/stations")

In [ ]:
result

In [ ]:
src = result.text
document = BeautifulSoup(src, 'lxml')

In [ ]:
table = document.find("table")

In [ ]:
table

In [ ]:
rows = table.find_all("tr")  # Note: this works because find_all is resursive by default

In [ ]:
rows

In [ ]:
#For getting all information from 1 page 
for row in rows[2:-1]:
    cells = row.find_all(["td", "th"])
    cells_text = [cell.get_text(strip=True) for cell in cells]
    (ID, Status, Uptime, Country, Location, Ships, Distinct, Contributor) = cells_text    
    print(f"{ID}, {Status}, {Uptime}, {Country}, {Location}, {Ships} , {Distinct} , {Contributor}")

2766, , 0 %, Angola, Zaire, 0 , 0 ,
3061, , 100 %, Argentina, Buenos Aires, 33 , 33 ,
2864, , 0 %, Australia, Morayfield, 0 , 0 ,
2995, , 100 %, Australia, Kingston, 6 , 6 ,
3292, , 99 %, Australia, Oakleigh, Victoria, 5 , 5 , SARCNET
2999, , 100 %, Australia, Mount Hicks, 8 , 6 ,
2739, , 90 %, Australia, Townsville, 38 , 38 ,
2360, , 100 %, Australia, Port Hedland, 3 , 3 ,
2637, , 87 %, Australia, Devonport, 7 , 5 ,
2556, , 100 %, Australia, Franklin, 10 , 10 ,
2070, , 100 %, Australia, Nelson Bay, NSW, 53 , 39 ,
2936, , 94 %, Australia, Kettering, 22 , 22 ,
2801, , 0 %, Australia, Glenorcky, 0 , 0 ,
2502, , 100 %, Australia, Scarborough, 13 , 13 ,
2465, , 0 %, Australia, Darwin, 0 , 0 ,
2675, , 100 %, Australia, Sydney, 25 , 11 ,
2701, , 96 %, Australia, O'Connor, 64 , 64 ,
2288, , 100 %, Australia, Johanna, 5 , 5 ,
2234, , 97 %, Australia, Mt Arthur (N.Tasmania), 6 , 6 ,
2798, , 100 %, Austria, Linz, 27 , 27 ,
3175, , 100 %, Austria, Vienna, 2 , 0 ,
2520, , 100 %, Austria, Vienna, 14 , 10 ,
2984, , 100 %, Azerbaijan, Baku, 42 , 42 ,
2445, , 0 %, Bahamas, Freeport, 0 , 0 ,
2127, , 100 %, Belgium, Izegem, 145 , 0 ,
2300, , 100 %, Belgium, Antwerp Harbour 1, 471 , 28 , www.vemasys.com
2404, , 100 %, Belgium, Bruges, 154 , 17 , dotOcean
3152, , 100 %, Belgium, Zeebrugge, 203 , 27 , Citymesh
2061, , 100 %, Belgium, Ostend, 40 , 0 ,
3075, , 100 %, Belgium, Aalst, 3 , 3 ,
2276, , 100 %, Belgium, Schilde, 311 , 4 ,
3359, , 83 %, Belgium, Schoten, 46 , 2 ,
3459, , 100 %, Belgium, Oostende, 146 , 2 , Flanders Marine Institute
2723, , 0 %, Belgium, Antwerp Harbour 2, 0 , 0 , www.vemasys.com
3215, , 86 %, Belgium, Antwerp, 1 , 0 ,
2145, , 100 %, Belgium, Antwerp2, 506 , 43 , Tresco Engineering
2981, , 95 %, Belgium, Oostende, 118 , 1 ,
2292, , 100 %, Belgium, Gent, 428 , 250 ,
2546, , 100 %, Belgium, Merchtem, 26 , 3 ,
3249, , 88 %, Belgium, Antwerp, 133 , 0 ,
3483, , 9 %, Belgium, WIjnegem, 49 , 12 ,
2709, , 0 %, Belgium, Watervliet, St Laureins, 0 , 0 ,
3489, , 100 %, Brazil, Maceio, 3 , 3 ,
2929, , 0 %, Brazil, Curitiba, 0 , 0 ,
2517, , 100 %, Brazil, Belem, 171 , 53 ,
2850, , 100 %, Brazil, Fortaleza, 12 , 12 , German Aerospace Center (DLR)
3019, , 0 %, Bulgaria, Varna, 0 , 0 ,
2576, , 0 %, Bulgaria, Varna, 0 , 0 ,
2372, , 99 %, Canada, Vancouver, 133 , 29 ,

In [ ]:
#For fetching all information from page 1 to 49. 
#Similarily if we want to scrap all 936 pages then just change number 50 to 937.You will able to scrap all information
for page in list(range(1,50)):
  result = requests.get("https://www.aishub.net/stations?page={}".format(page))
  src = result.text
  document = BeautifulSoup(src, 'lxml')
  table = document.find("table")
  rows = table.find_all("tr")  # Note: this works because find_all is resursive by default
  for row in rows[2:-1]:
    cells = row.find_all(["td", "th"])
    cells_text = [cell.get_text(strip=True) for cell in cells]
    (ID, Status, Uptime, Country, Location, Ships, Distinct, Contributor) = cells_text    
    print(f"{ID}, {Status}, {Uptime}, {Country}, {Location}, {Ships} , {Distinct} , {Contributor}")

2766, , 0 %, Angola, Zaire, 0 , 0 ,
3061, , 100 %, Argentina, Buenos Aires, 16 , 16 ,
2864, , 0 %, Australia, Morayfield, 0 , 0 ,
2675, , 100 %, Australia, Sydney, 31 , 14 ,
2701, , 96 %, Australia, O'Connor, 62 , 62 ,
2936, , 94 %, Australia, Kettering, 23 , 21 ,
2070, , 100 %, Australia, Nelson Bay, NSW, 57 , 40 ,
2360, , 100 %, Australia, Port Hedland, 7 , 6 ,
2465, , 0 %, Australia, Darwin, 0 , 0 ,
2556, , 100 %, Australia, Franklin, 11 , 9 ,
2234, , 97 %, Australia, Mt Arthur (N.Tasmania), 4 , 4 ,
2739, , 90 %, Australia, Townsville, 37 , 37 ,
2801, , 0 %, Australia, Glenorcky, 0 , 0 ,
2502, , 100 %, Australia, Scarborough, 14 , 14 ,
3292, , 99 %, Australia, Oakleigh, Victoria, 4 , 4 , SARCNET
2995, , 100 %, Australia, Kingston, 7 , 6 ,
2637, , 87 %, Australia, Devonport, 8 , 6 ,
2999, , 100 %, Australia, Mount Hicks, 9 , 7 ,
2288, , 100 %, Australia, Johanna, 7 , 7 ,
2798, , 100 %, Austria, Linz, 27 , 27 ,
3175, , 100 %, Austria, Vienna, 2 , 0 ,
2520, , 100 %, Austria, Vienna, 20 , 17 ,
2984, , 100 %, Azerbaijan, Baku, 54 , 54 ,
2445, , 0 %, Bahamas, Freeport, 0 , 0 ,
2127, , 100 %, Belgium, Izegem, 118 , 0 ,
3459, , 100 %, Belgium, Oostende, 77 , 2 , Flanders Marine Institute
3075, , 100 %, Belgium, Aalst, 1 , 1 ,
2300, , 100 %, Belgium, Antwerp Harbour 1, 398 , 7 , www.vemasys.com
2404, , 100 %, Belgium, Bruges, 153 , 27 , dotOcean
2723, , 0 %, Belgium, Antwerp Harbour 2, 0 , 0 , www.vemasys.com
3359, , 83 %, Belgium, Schoten, 37 , 0 ,
2276, , 100 %, Belgium, Schilde, 323 , 10 ,
2061, , 100 %, Belgium, Ostend, 33 , 0 ,
3483, , 9 %, Belgium, WIjnegem, 42 , 16 ,
2709, , 0 %, Belgium, Watervliet, St Laureins, 0 , 0 ,
3215, , 86 %, Belgium, Antwerp, 0 , 0 ,
3249, , 88 %, Belgium, Antwerp, 89 , 0 ,
2981, , 95 %, Belgium, Oostende, 105 , 0 ,
2546, , 100 %, Belgium, Merchtem, 36 , 4 ,
3152, , 100 %, Belgium, Zeebrugge, 210 , 42 , Citymesh
2145, , 100 %, Belgium, Antwerp2, 537 , 93 , Tresco Engineering
2292, , 100 %, Belgium, Gent, 423 , 254 ,
2517, , 100 %, Brazil, Belem, 175 , 53 ,
3489, , 100 %, Brazil, Maceio, 3 , 3 ,
2850, , 100 %, Brazil, Fortaleza, 9 , 9 , German Aerospace Center (DLR)
2929, , 0 %, Brazil, Curitiba, 0 , 0 ,
3019, , 0 %, Bulgaria, Varna, 0 , 0 ,
2576, , 0 %, Bulgaria, Varna, 0 , 0 ,
2512, , 100 %, Canada, Quadra Island, 70 , 62 ,
2025, , 100 %, Canada, Windsor, Ontario, 8 , 8 ,
3103, , 100 %, Canada, Multiple Locations, 125 , 3 ,
2920, , 57 %, Canada, Burnaby, 23 , 1 ,
2218, , 100 %, Canada, Newfoundland, St. Johns, 2 , 2 ,
2372, , 99 %, Canada, Vancouver, 124 , 31 ,
2848, , 100 %, Canada, Victoria, 63 , 1 ,
2042, , 100 %, Canada, Vancouver, 128 , 18 ,
2853, , 100 %, Canada, Vancouver, 15 , 2 ,
2857, , 100 %, Canada, Vancouver, 39 , 0 ,
2019, , 100 %, Canada, Victoria, BC, 35 , 1 ,
3185, , 100 %, Canada, Halifax, 39 , 17 ,
2890, , 100 %, Canada, Montreal, 25 , 1 ,
2955, , 99 %, Canada, Bowen Island, 184 , 29 ,
2215, , 73 %, Canada, Burnaby, 0 , 0 ,
2253, , 97 %, Canada, Montreal, 7 , 2 ,
2818, , 93 %, Canada, Montreal, 32 , 10 ,
2202, , 100 %, Canada, Ucluelet, 22 , 19 ,
2821, , 100 %, Canada, Burnaby, 29 , 1 ,
3201, , 94 %, Canada, Sorel-Tracy, 17 , 0 ,
2017, , 100 %, Canada, Corner Brook, 16 , 16 ,
2676, , 100 %, Canada, Toronto, 11 , 11 ,
3083, , 100 %, Canada, New Westminster, 38 , 18 ,
2700, , 92 %, Canada, Sorel-Tracy, 22 , 2 ,
2593, , 100 %, Canada, Prince Rupert, 63 , 16 ,
3145, , 100 %, Canada, Vancouver, 370 , 140 ,
2660, , 56 %, Canada, Sorel-Tracy, 0 , 0 ,
2463, , 100 %, Canada, Prince Rupert, 49 , 2 ,
3238, , 100 %, Canada, East Point Saturna Island, 28 , 3 ,
2267, , 100 %, Canada, Dartmouth, 23 , 1 ,
3248, , 33 %, Chile, Concon, 0 , 0 ,
2348, , 96 %, Chile, Viña del Mar, 18 , 18 ,
3031, , 100 %, China, Jiangyin & Maanshan, 674 , 672 ,
2193, , 100 %, China, Xia Men, 117 , 117 ,
2113, , 0 %, China, Xiawan, 0 , 0 ,
2930, , 100 %, China, Chongqing, 3 , 2 ,
2456, , 100 %, China, Haikou, 1120 , 1116 ,
2969, , 100 %, China, Meizhou Bay, 150 , 1 ,
2632, , 100 %, China, Shenzhen, 75 , 52 ,
2151, , 0 %, China, Dalian, 0 , 0 ,
2083, , 100 %, China, Yangpu, 383 , 298 ,
2587, , 100 %, China, Beijing, 238 , 238 ,
2598, , 100 %, China, Beijing, 268 , 266 ,
2044, , 100 %, China, Fujian, 99 , 99 ,
2356, , 100 %, China, Zhangjiagang, 6 , 6 ,
2866, , 100 %, Colombia, Puerto Colombia, 16 , 16 ,
2443, , 0 %, Colombia, Barranquilla, 0 , 0 ,
2362, , 87 %, Colombia, Buenaventura, 24 , 24 , Pacific Pilots
3439, , 91 %, Croatia, Kraljevica, 41 , 40 ,
2690, , 96 %, Croatia, Štinjan, Pula, 26 , 17 ,
2524, , 100 %, Cyprus, Limassol, 23 , 18 ,
2255, , 28 %, Cyprus, Limassol, 0 , 0 ,
2104, , 99 %, Denmark, Gershøj, 9 , 3 ,
2621, , 100 %, Denmark, Aalborg, 30 , 20 ,
2139, , 100 %, Denmark, Islands Brygge, 171 , 61 ,
3179, , 100 %, Denmark, Aarhus, 23 , 15 ,
3424, , 100 %, Denmark, Holbæk, 10 , 9 ,
2899, , 100 %, Denmark, Ringsted, 14 , 11 ,
2545, , 100 %, Denmark, Sletten, 71 , 5 ,
2327, , 100 %, Denmark, Roenne, Bornholm, 16 , 16 ,
2828, , 100 %, Denmark, Skive, 7 , 6 ,
2400, , 100 %, Denmark, Norresundby, 22 , 22 ,
3361, , 100 %, Denmark, Korsør, 18 , 18 ,
2058, , 100 %, Denmark, Humlebaek, 95 , 16 ,
2580, , 100 %, Denmark, Frederikssund, 14 , 9 ,
3417, , 0 %, Denmark, Ebeltoft, 0 , 0 ,
2725, , 100 %, Denmark, Aarhus, 10 , 3 ,
3130, , 100 %, Denmark, Lunderskov, 121 , 94 ,
3421, , 100 %, Denmark, Marstal, 36 , 20 ,
3497, , 100 %, Denmark, Rødby, 82 , 10 ,
2566, , 100 %, Estonia, Tallinn, 1 , 0 ,
2479, , 100 %, Estonia, Tallinn, 107 , 34 ,
2527, , 77 %, Estonia, Vaana-Joesuu, 4 , 0 ,
2811, , 100 %, Estonia, Tallinn, 20 , 1 ,
3340, , 100 %, Estonia, Tallinn, 29 , 0 ,
3452, , 100 %, Estonia, Tallinn, 4 , 0 ,
3060, , 0 %, Finland, Mariehamn, 0 , 0 ,
2190, , 29 %, Finland, Ekenas, 20 , 20 ,
2867, , 0 %, Finland, Vantaa, 0 , 0 ,
2380, , 100 %, Finland, Helsinki, 103 , 97 ,
3054, , 94 %, Finland, Turku, 4 , 0 ,
2695, , 100 %, Finland, Turku, 42 , 38 ,
2388, , 100 %, Finland, Finland, 141 , 75 , Pocket Mariner
2049, , 0 %, Finland, Kotka, 0 , 0 ,
2481, , 90 %, Finland, Vaasa, 1 , 0 ,
3155, , 99 %, Finland, Kokkola, 11 , 11 ,
2264, , 100 %, Finland, Uto, 6 , 6 ,
2486, , 100 %, France, Saint Xandre, 41 , 3 ,
3319, , 0 %, France, Toulon, 0 , 0 ,
2617, , 0 %, France, Paimpol, 0 , 0 ,
2095, , 25 %, France, Bezons, 1 , 1 ,
2156, , 100 %, France, Aubervilliers, 5 , 5 ,
2289, , 0 %, France, Six Fours Les Plages, 0 , 0 ,
2195, , 0 %, France, Nice, 0 , 0 ,
3330, , 9 %, France, Lyon, 0 , 0 ,
2335, , 69 %, France, Le Havre, 165 , 0 ,
2972, , 100 %, France, Brest, 83 , 28 ,
2653, , 100 %, France, La Rochelle, 52 , 15 ,
2572, , 99 %, France, Mandelieu La Napoule, 16 , 1 ,
2037, , 100 %, France, France, 99 , 28 ,
2102, , 100 %, France, Antibes, 46 , 1 ,
2749, , 100 %, France, Carnon, 51 , 27 ,
2617, , 0 %, France, Paimpol, 0 , 0 ,
3228, , 75 %, France, Carantec, 14 , 14 ,
2730, , 99 %, France, Sète, 60 , 48 ,
2662, , 100 %, France, Le Havre, 219 , 3 ,
2156, , 100 %, France, Aubervilliers, 5 , 5 ,
2972, , 100 %, France, Brest, 83 , 28 ,
2195, , 0 %, France, Nice, 0 , 0 ,
3118, , 0 %, France, Thomery, 0 , 0 ,
2166, , 100 %, France, Saint Georges de Didonnes, 14 , 0 , SailGrib
2178, , 100 %, France, Rouen, 84 , 28 ,
2954, , 100 %, France, Sophia Antipolis, MINES Paristech, 308 , 192 , MINES Paristech
2486, , 100 %, France, Saint Xandre, 41 , 3 ,
2415, , 100 %, France, Brest, 39 , 0 ,
2095, , 25 %, France, Bezons, 1 , 1 ,
2836, , 100 %, France, Brest, 53 , 1 ,
2693, , 100 %, France, Paris, 16 , 0 , SailGrib
2887, , 100 %, France, Plouzané, 25 , 0 ,
2487, , 100 %, France, Fecamp, 10 , 7 ,
2320, , 100 %, France, Brest, 21 , 0 ,
3319, , 0 %, France, Toulon, 0 , 0 ,
2557, , 85 %, France, Grasse, 18 , 7 ,
3240, , 0 %, France, Ajaccio, 0 , 0 ,
2817, , 100 %, France, Palavas les Flots, 16 , 1 ,
2038, , 100 %, France, Port de Bouc, 23 , 23 ,
3162, , 0 %, France, Cléden-Cap-Sizun, 0 , 0 ,
2960, , 53 %, France, Melun, 0 , 0 ,
2275, , 100 %, France, Lorient, 56 , 15 ,
2467, , 100 %, France, La Seyne sur Mer, 15 , 15 ,
2564, , 0 %, France, La Rochelle, 0 , 0 ,
2428, , 100 %, France, Le Havre, 108 , 0 ,
3330, , 9 %, France, Lyon, 0 , 0 ,
2774, , 100 %, France, Bidart, 7 , 4 ,
2869, , 0 %, France, Calvi, 0 , 0 ,
2471, , 100 %, France, UBS-Vannes, 56 , 17 ,
2777, , 0 %, France, Sarzon, 0 , 0 ,
2805, , 100 %, Germany, Norderney, 44 , 31 ,
3453, , 64 %, Germany, Garbsen, 1 , 1 ,
2186, , 100 %, Germany, Könau, 11 , 11 ,
2877, , 83 %, Germany, Dormagen, 23 , 0 ,
2531, , 74 %, Germany, Frankfurt, 2 , 0 ,
2663, , 43 %, Germany, Lingen, 1 , 1 ,
2754, , 100 %, Germany, Barrien, 10 , 0 ,
3496, , 50 %, Germany, Ostseebad Kühlungsborn, 0 , 0 ,
3232, , 99 %, Germany, Cologne, 124 , 5 ,
2568, , 0 %, Germany, Wesel, 0 , 0 ,
2784, , 100 %, Germany, Emden, 62 , 14 ,
2603, , 100 %, Germany, Geesthacht, 161 , 20 ,
2582, , 96 %, Germany, Siegburg, 2 , 0 ,
2717, , 100 %, Germany, Heilbronn, 8 , 8 ,
2238, , 0 %, Germany, Bremen, 0 , 0 ,
2759, , 100 %, Germany, Bruehl-Baden, 31 , 1 ,
2543, , 100 %, Germany, Hamburg, 195 , 2 ,
2561, , 100 %, Germany, Bremerhaven, 23 , 0 ,
2738, , 100 %, Germany, Hamburg, 93 , 0 ,
3366, , 98 %, Germany, Lüneburg, 2 , 0 ,
2605, , 0 %, Germany, Hamburg, 0 , 0 ,
3170, , 100 %, Germany, Bonn, 6 , 0 , inducto Information
2673, , 0 %, Germany, Hamburg, 0 , 0 ,
2805, , 100 %, Germany, Norderney, 44 , 31 ,
2223, , 100 %, Germany, Bremen Winterhafen, 12 , 0 ,
3066, , 100 %, Germany, Düsseldorf, 1 , 1 ,
2030, , 100 %, Germany, Rostock, 99 , 47 ,
2216, , 11 %, Germany, Ruesselsheim am Main, 0 , 0 ,
2877, , 83 %, Germany, Dormagen, 23 , 0 ,
2228, , 100 %, Germany, Kiel, 142 , 40 ,
2403, , 100 %, Germany, Stadersand, 152 , 11 ,
2784, , 100 %, Germany, Emden, 62 , 14 ,
2291, , 100 %, Germany, Bremerhaven, 210 , 24 , North Sea Terminal Bremerhaven GmbH & Co.
2958, , 100 %, Germany, Dettelbach, 5 , 5 ,
3232, , 99 %, Germany, Cologne, 124 , 5 ,
2165, , 100 %, Germany, Hamburg, 379 , 0 ,
2747, , 100 %, Germany, Wilhelmshaven, 50 , 1 ,
2728, , 100 %, Germany, Emden, 41 , 0 ,
2860, , 100 %, Germany, Berlin, 1 , 1 ,
2551, , 96 %, Germany, Elbe River, Drochtersen, 42 , 1 ,
2461, , 100 %, Germany, Dresden, 5 , 3 ,
2633, , 100 %, Germany, Bremen, 21 , 0 ,
2413, , 100 %, Germany, Hamburg Alster, 379 , 0 , www.searoutes.com
3236, , 85 %, Germany, Flörsheim, 1 , 1 ,
3453, , 64 %, Germany, Garbsen, 1 , 1 ,
3392, , 100 %, Germany, Lienen, 149 , 9 ,
2359, , 100 %, Germany, Neuruppin, 17 , 16 ,
2733, , 100 %, Germany, Berlin, 1 , 1 ,
3132, , 0 %, Germany, Hamburg, 0 , 0 ,
3496, , 50 %, Germany, Ostseebad Kühlungsborn, 0 , 0 ,
2865, , 100 %, Germany, Frankfurt, 17 , 15 ,
3160, , 100 %, Germany, Wildau, 2 , 1 ,
3190, , 0 %, Germany, Hamburg, 0 , 0 ,
2398, , 100 %, Germany, Berlin, 70 , 19 ,
2577, , 100 %, Germany, Hamburg, 341 , 14 ,
2126, , 100 %, Germany, Cologne, 290 , 122 ,
2167, , 100 %, Germany, BIBA, 19 , 0 , BIBA AIS
2737, , 100 %, Germany, Hamburg, 129 , 0 ,
3364, , 100 %, Germany, Mönchhagen, 63 , 25 ,
2176, , 100 %, Germany, Glueckstadt, 22 , 3 ,
2793, , 100 %, Germany, Wismar, 18 , 3 ,
2861, , 100 %, Germany, Karlsruhe, 64 , 54 , Fraunhofer IOSB
2551, , 96 %, Germany, Elbe River, Drochtersen, 42 , 1 ,
2396, , 0 %, Germany, Neuss, 0 , 0 ,
2030, , 100 %, Germany, Rostock, 99 , 47 ,
3266, , 100 %, Germany, Mannheim, 94 , 14 ,
3097, , 100 %, Germany, Wilhelmshaven, 288 , 106 ,
2663, , 43 %, Germany, Lingen, 1 , 1 ,
3066, , 100 %, Germany, Düsseldorf, 1 , 1 ,
2754, , 100 %, Germany, Barrien, 10 , 0 ,
2291, , 100 %, Germany, Bremerhaven, 210 , 24 , North Sea Terminal Bremerhaven GmbH & Co.
2461, , 100 %, Germany, Dresden, 5 , 3 ,
2167, , 100 %, Germany, BIBA, 19 , 0 , BIBA AIS
2176, , 100 %, Germany, Glueckstadt, 22 , 3 ,
2165, , 100 %, Germany, Hamburg, 379 , 0 ,
2207, , 100 %, Germany, Wismar, 17 , 2 ,
2717, , 100 %, Germany, Heilbronn, 8 , 8 ,
2958, , 100 %, Germany, Dettelbach, 5 , 5 ,
3384, , 100 %, Germany, Bremen, Arsten, 47 , 0 ,
2359, , 100 %, Germany, Neuruppin, 17 , 16 ,
2759, , 100 %, Germany, Bruehl-Baden, 31 , 1 ,
2561, , 100 %, Germany, Bremerhaven, 23 , 0 ,
2137, , 100 %, Germany, Bremen, 91 , 7 ,
2738, , 100 %, Germany, Hamburg, 93 , 0 ,
3281, , 0 %, Germany, Bonn, 0 , 0 ,
3425, , 100 %, Germany, Hamburg, 16 , 0 ,
2237, , 96 %, Greece, Athens, Glyfada, 307 , 8 ,
2118, , 97 %, Greece, Alimos, 280 , 1 ,
2226, , 86 %, Greece, Athens, 167 , 2 ,
3036, , 100 %, Greece, Piraeus, 14 , 0 ,
2084, , 100 %, Greece, Ios, 38 , 38 , Ios Hellas
2871, , 60 %, Greece, Athens, 8 , 8 ,
3197, , 100 %, Greece, Thessaloniki, 16 , 16 ,
2290, , 100 %, Greece, Athens, 80 , 29 ,
2746, , 47 %, Greece, Rafina, 0 , 0 ,
2339, , 100 %, Greece, North Aegean, 18 , 18 ,
3038, , 0 %, Greece, Piraeus, 0 , 0 ,
3344, , 93 %, Greece, Athens, 410 , 103 ,
2316, , 76 %, Guernsey, Guernsey, 25 , 0 ,
2654, , 100 %, Guernsey, St Martin, 50 , 21 ,
3202, , 100 %, Hong Kong, Tsuen Wan, 77 , 18 ,
3272, , 100 %, Hong Kong, Tseung Kwan O, 30 , 17 ,
2177, , 100 %, Hong Kong, Kowloon, 228 , 163 ,
3048, , 100 %, Hong Kong, Tung Chung, 417 , 413 ,
2785, , 90 %, Hong Kong, Aberdeen, 5 , 3 ,
3302, , 40 %, Iceland, Reykjavik, 4 , 4 ,
2670, , 23 %, India, At Sea, 0 , 0 ,
3399, , 98 %, Indonesia, Ambon - Maluku, 28 , 28 ,
3015, , 100 %, Indonesia, Balikpapan, East Kalimantan, 661 , 125 ,
3016, , 100 %, Indonesia, Jakarta, 14 , 14 ,
3357, , 87 %, Ireland, Inishbofin, 4 , 4 ,
2085, , 100 %, Ireland, Kinsale, 30 , 11 ,
2569, , 95 %, Ireland, Galway, 3 , 3 ,
2354, , 61 %, Ireland, Mizen Head, 0 , 0 ,
3053, , 42 %, Ireland, Renvyle, 0 , 0 ,
2150, , 99 %, Ireland, Lackenbehy, 13 , 0 ,
2441, , 22 %, Ireland, Ring, 0 , 0 ,
3104, , 100 %, Ireland, Bangor, 39 , 36 ,
2378, , 78 %, Ireland, Newtownmountkennedy, 4 , 0 ,
2321, , 100 %, Ireland, Cobh, 18 , 0 ,
2846, , 53 %, Ireland, Westport, 1 , 0 ,
3304, , 100 %, Ireland, Newcastle, 18 , 14 ,
2610, , 99 %, Israel, Haifa, 7 , 6 ,
2283, , 100 %, Israel, Haifa, 10 , 9 ,
2371, , 100 %, Israel, Haifa, 57 , 0 ,
2893, , 100 %, Israel, Haifa, 124 , 67 ,
2751, , 14 %, Israel, Tel Aviv, 0 , 0 ,
2521, , 43 %, Italy, Gela, 5 , 5 ,
2489, , 100 %, Italy, Messina, 131 , 89 ,
3100, , 81 %, Italy, Naples, 12 , 1 ,
3224, , 98 %, Italy, San Benedetto del Tronto, 25 , 25 ,
2169, , 100 %, Italy, La Spezia, 308 , 216 ,
2525, , 99 %, Italy, Meta (Naples), 81 , 14 ,
2573, , 100 %, Italy, Venice, 113 , 73 ,
2394, , 100 %, Italy, Livorno, 50 , 3 ,
3116, , 100 %, Italy, Sorrento, 78 , 12 ,
2914, , 0 %, Italy, Ischia, 0 , 0 ,
2873, , 53 %, Italy, Licata, 2 , 2 ,
2098, , 100 %, Italy, Palermo, 33 , 33 ,
2189, , 100 %, Italy, Milazzo, 84 , 84 ,
2553, , 100 %, Italy, Aprilia, 27 , 27 ,
2217, , 100 %, Italy, Taranto, 24 , 24 ,
2326, , 100 %, Japan, Sumoto, 77 , 44 ,
2171, , 100 %, Japan, Chiba, 13 , 13 ,
2947, , 100 %, Japan, Yokohama (JP YOK), 56 , 27 ,
2062, , 100 %, Japan, Yokosuka, 124 , 15 ,
3163, , 100 %, Japan, Kobe, 183 , 58 ,
2121, , 100 %, Japan, Kobe, 116 , 2 ,
3114, , 0 %, Japan, Yokohama, Kanagawa, 0 , 0 ,
2119, , 77 %, Japan, Yokohama, 234 , 108 ,
2417, , 100 %, Japan, Wakayama Port, 29 , 24 ,
3024, , 100 %, Japan, Katsuura, Chiba, 64 , 58 ,
3402, , 57 %, Korea, Incheon, 51 , 11 ,
2391, , 98 %, Korea, Pyuntaek, 88 , 44 ,
3322, , 100 %, Korea, Busan, 70 , 70 ,
2991, , 97 %, Korea, Jejusi, 11 , 11 ,
3188, , 100 %, Kuwait, Kuwait, 43 , 43 ,
2719, , 100 %, Lithuania, Klaipeda, 55 , 55 ,
2138, , 92 %, Mexico, Veracruz, 12 , 12 ,
2427, , 100 %, Mexico, Cozumel, 8 , 8 ,
3043, , 100 %, Monaco, Monaco, 32 , 0 ,
2822, , 31 %, Monaco, Monaco, 87 , 39 ,
3241, , 100 %, Morocco, Casablanca, 237 , 89 ,
3411, , 0 %, Morocco, Casablanca, 0 , 0 ,
2425, , 100 %, Netherlands, Ter Walslage, 9 , 9 ,
2077, , 100 %, Netherlands, Rotterdam, 967 , 50 ,
3473, , 100 %, Netherlands, Breskens, 45 , 22 ,
2671, , 100 %, Netherlands, Hippolytushoef, 114 , 53 ,
2590, , 100 %, Netherlands, Breda, 73 , 42 ,
3183, , 100 %, Netherlands, Harlingen, 371 , 0 ,
2921, , 0 %, Netherlands, Zeist, 0 , 0 ,
2652, , 100 %, Netherlands, Marknesse, 206 , 40 ,
3027, , 66 %, Netherlands, Amstelveen, 1 , 0 ,
3159, , 100 %, Netherlands, Gendt, 36 , 1 ,
2771, , 100 %, Netherlands, West-Terschelling, 85 , 17 , Maritime Institute Willem Barentsz
2287, , 100 %, Netherlands, Rosmalen, 27 , 12 ,
2409, , 100 %, Netherlands, Geertruidenberg, 176 , 101 ,
2475, , 100 %, Netherlands, Poortugaal, 226 , 2 ,
2278, , 100 %, Netherlands, Amsterdam, 615 , 22 ,
2674, , 98 %, Netherlands, Maastricht, 1 , 1 ,
2239, , 100 %, Netherlands, Goor, 7 , 7 ,
3078, , 0 %, Netherlands, Amsterdam, 0 , 0 ,
3390, , 99 %, Netherlands, Alphen aan den Rijn, 17 , 0 ,
2435, , 100 %, Netherlands, Katwijk, 393 , 26 ,
2623, , 100 %, Netherlands, Appeltern, 193 , 109 ,
2775, , 100 %, Netherlands, Franeker, 110 , 3 ,
2596, , 99 %, Netherlands, Utrecht, 19 , 1 ,
2987, , 100 %, Netherlands, Vogelwaarde, Zeeland, 264 , 122 ,
2697, , 100 %, Netherlands, Wadscan AIS, 371 , 0 ,
3135, , 100 %, Netherlands, Koog aan de Zaan, 251 , 8 ,
2554, , 100 %, Netherlands, Gorinchem, 33 , 4 ,
2347, , 100 %, Netherlands, The Hague, 224 , 19 ,
2961, , 100 %, Netherlands, Rijswijk, 65 , 1 ,
3429, , 100 %, Netherlands, Terneuzen, 31 , 0 ,
2852, , 100 %, Netherlands, Born, 18 , 16 ,
2625, , 99 %, Netherlands, Sint Anne, 3 , 0 ,
3317, , 100 %, Netherlands, Veere, 21 , 1 ,
3166, , 99 %, Netherlands, Zaandam, 256 , 12 ,
2778, , 0 %, Netherlands, Botlek, 0 , 0 ,
3288, , 0 %, Netherlands, Dordrecht, 0 , 0 ,
3006, , 100 %, Netherlands, Heerenveen, 3 , 3 ,
2497, , 100 %, Netherlands, Warmond, 26 , 4 ,
2232, , 88 %, Netherlands, Rotterdam, 7 , 0 ,
2097, , 100 %, Netherlands, Hellevoetsluis, 565 , 32 , InterTransIS
2298, , 73 %, Netherlands, Rotterdam, 13 , 12 ,
2679, , 100 %, Netherlands, Urk, 334 , 1 ,
3082, , 100 %, Netherlands, Alphen Aan Den Rijn, 17 , 0 ,
2771, , 100 %, Netherlands, West-Terschelling, 85 , 17 , Maritime Institute Willem Barentsz
2574, , 63 %, Netherlands, Zwolle, 2 , 0 ,
2140, , 100 %, Netherlands, Rotterdam, 209 , 2 ,
2239, , 100 %, Netherlands, Goor, 7 , 7 ,
3212, , 100 %, Netherlands, Maarssenbroek, 13 , 1 ,
2549, , 100 %, Netherlands, Rijswijk, 598 , 6 ,
2674, , 98 %, Netherlands, Maastricht, 1 , 1 ,
2475, , 100 %, Netherlands, Poortugaal, 226 , 2 ,
3295, , 100 %, Netherlands, Eijsden, 12 , 12 ,
3126, , 0 %, Netherlands, Rotterdam, 0 , 0 ,
2775, , 100 %, Netherlands, Franeker, 110 , 3 ,
2588, , 100 %, Netherlands, The Hague, 369 , 1 ,
3004, , 88 %, Netherlands, Rotterdam, 7 , 0 ,
2435, , 100 %, Netherlands, Katwijk, 393 , 26 ,
2214, , 100 %, Netherlands, Rotterdam, 418 , 0 ,
3412, , 100 %, Netherlands, Rotterdam, 92 , 0 ,
2697, , 100 %, Netherlands, Wadscan AIS, 371 , 0 ,
3182, , 0 %, Netherlands, Delft, 0 , 0 ,
2596, , 99 %, Netherlands, Utrecht, 19 , 1 ,
2852, , 100 %, Netherlands, Born, 18 , 16 ,
2554, , 100 %, Netherlands, Gorinchem, 33 , 4 ,
3056, , 100 %, Netherlands, Leiden, 75 , 4 ,
2086, , 100 %, Netherlands, Katwijk, 156 , 0 ,
2778, , 0 %, Netherlands, Botlek, 0 , 0 ,
3007, , 100 %, Netherlands, Maarssen, 24 , 3 ,
2298, , 73 %, Netherlands, Rotterdam, 13 , 12 ,
2381, , 100 %, Netherlands, Delft, 5 , 0 ,
3372, , 100 %, Netherlands, Wijchen, 70 , 8 ,
2679, , 100 %, Netherlands, Urk, 334 , 1 ,
2497, , 100 %, Netherlands, Warmond, 26 , 4 ,
2077, , 100 %, Netherlands, Rotterdam, 967 , 50 ,
2097, , 100 %, Netherlands, Hellevoetsluis, 565 , 32 , InterTransIS
2287, , 100 %, Netherlands, Rosmalen, 27 , 12 ,
2273, , 100 %, Netherlands, Rotterdam, 103 , 0 ,
2878, , 0 %, Netherlands, Brielle, 0 , 0 ,
3381, , 100 %, Netherlands, Hoogvliet, 192 , 1 ,
2278, , 100 %, Netherlands, Amsterdam, 615 , 22 ,
2379, , 100 %, Netherlands, Zeist, 33 , 8 , QPS
3136, , 62 %, Netherlands, Zwolle, 0 , 0 ,
2468, , 100 %, Netherlands, Rotterdam, 384 , 26 , InterTransIS
2607, , 100 %, Netherlands, Amsterdam, 106 , 1 ,
3252, , 0 %, Netherlands, Waalre, 0 , 0 ,
2347, , 100 %, Netherlands, The Hague, 224 , 19 ,
2220, , 96 %, Netherlands, Tolkamer, 2 , 0 ,
3199, , 100 %, Netherlands, Rotterdam, 17 , 0 ,
3284, , 100 %, Netherlands, Lelystad, 207 , 12 ,
2712, , 100 %, Netherlands, Oostburg, 19 , 1 ,
3254, , 100 %, Netherlands, Emmeloord, 126 , 0 ,
2734, , 99 %, Netherlands, Driebergen, 7 , 2 ,